name: Bug Report
description: Report a bug in ArchiCode.js
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: ArchiCode.js Version
      description: What version of ArchiCode.js are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running ArchiCode.js?
      options:
        - Browser (Chrome)
        - Browser (Firefox)
        - Browser (Safari)
        - Browser (Edge)
        - Node.js
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Load ArchiCode.js
        2. Use this code: '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: archimate-code
    attributes:
      label: ArchiMate Code
      description: The ArchiMate code that causes the issue
      render: text
      placeholder: |
        [<business:actor> Example]
        [Example] --> [Another Element]

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: Console Output
      description: Any error messages or console output
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here